"""empty message

Revision ID: 92847be4b8fd
Revises: 
Create Date: 2021-03-20 01:03:52.621991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92847be4b8fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('dosen_id', sa.String(), nullable=False),
    sa.Column('dosen', sa.String(), nullable=False),
    sa.Column('dosen_judul_id', sa.String(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details')
    op.drop_table('queries')
    # ### end Alembic commands ###
